= Containers and Python
include::_attributes.adoc[]

[#introduction]
== Introduction to Podman

With a simple example application, the next step is to run the code using a container. Docker is the most common tool however, Podman is Red Hat's open source equivalent. It so similar you can even install a package that allows you to invoke Podman commands using the `docker` command. 

[source%nowrap,console]
----
$ sudo dnf install podman-docker 
----

On a Red Hat Enterprse Linux system, install Podman:

[source%nowrap,console]
----
sudo dnf install podman buildah -y
----

Explore the `ubi/python-39` image:

[source%nowrap,console]
----
podman run -it ubi8/python-39:latest /bin/bash
----

[source%nowrap,console]
----
(app-root) pwd
/opt/app-root/src
(app-root) ls -al
(app-root) exit
----

[#dockerfile]
=== Dockerfile

The previous exploration tell us that the default current working directory is `/opt/app-root/src`, and we know OpenShift will not run containers as `root`.ca

Add a `Dockerfile`:

[source%nowrap,docker]
----
FROM ubi8/python-39

LABEL maintainer="Richard Walker"

USER root

WORKDIR /opt/app-root/src

COPY . /opt/app-root/src

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN chown -R 1001:1001 /opt/app-root/src

USER 1001

EXPOSE 8000

CMD python main.py
----

Point the `FROM` image to an internal image that is accessible and meets the requirements.

Ensure the Python Virtual Environment is activated:

[source%nowrap,console]
----
$ . venv/bin/activate 
----

If not already done, freeze the requirements for the project, for example:

[source%nowrap,console]
----
pip freeze > requirements.txt
----

The directory tree should look like this:

[source%nowrap,console]
----
.
├── api
│   └── motd.py
├── Dockerfile
├── main.py
├── requirements.txt
├── static
│   └── img
│       └── fastapi_logo.png
├── templates
│   ├── _base.html
│   └── home.html
├── test_main.py
├── views
│   └── home.py
└── venv
----

Use Podman to build a local image:

[source%nowrap,console]
----
podman build -t local/fastapi-quickstart:latest .
----

Use `podman images` to list local images and use `podman rmi <IMAGE>` to delete them.

Run the application using Podman, passing in the environment variable at runtime with:

[source%nowrap,console]
----
podman run -d -p 8000:8000 -e ENV_STRING="Hello World" local/fastapi-quickstart:latest
----

[source%nowrap,console]
----
podman ps
----

That's all there is to it! Test the application at http://localhost:8000/